Universidad/grails-app/domain/com/qvision/Libro.groovy
package com.qvision
import com.qvision.Reservas

class Libro {

	static hasMany = [libro: Reservas]

	String nombre

    static constraints = {
    	nombre 	blank: false
    }

	static mapping = {
    	version 	false
    }
}

Universidad/grails-app/controllers/com/qvision/LibroController.groovy
package com.qvision
import com.qvision.Libro
import grails.plugin.springsecurity.annotation.Secured

@Secured('ROLE_ADMIN')
class LibroController {

    def index() {
        def listaLibros = Libro.list()
        render view : "libro", model: [lista: listaLibros]
    }

    def editarLibro() {
        def libroId = Libro.get(params.id)
        render view : "editarLibro", model : [libro: libroId]
    }

    def updateLibro() {
        def libroId = Libro.get(params.id)
        libroId.setNombre(params.nombre)
        libroId.save(flush:true,failOnError:true)
        redirect view:"libro"
    }

    def eliminarLibro() {
        def libroId = Libro.get(params.id)
        libroId.delete(flush:true, failOnError:true)
        redirect view:"libro"
    }

    def agregarLibro() {
        render view:"agregarLibro"
    }

    def guardarLibro(){
        def libro = new Libro(nombre:params.nombre)
        libro.save(flush:true,failOnError:true)
        redirect view:"index"
     }
}

Universidad/grails-app/controllers/com/qvision/ReservasController.groovy
package com.qvision
import com.qvision.Libro
import com.qvision.Reservas
import grails.plugin.springsecurity.annotation.Secured
import java.util.Date

@Secured('ROLE_ADMIN')
class ReservasController {

    def estudiante

    def index() { 
    	
    	if (Estudiante.get(params.id) != null) 
            estudiante = Estudiante.get(params.id)
       
        def listaReservas = Reservas.withCriteria {
            estudiante {
                eq('id',estudiante.getId())
            }
        }
        println listaReservas

    	render view:"reserva",model:[lista:listaReservas,estudianteNombre:estudiante]
    }

    def goBack() {
        render view:"menu",model:[estudianteNombre:estudiante]
    }

    def goReservar(){
        def listaLibros = Libro.list()
        render view:"reservar",model:[lista:listaLibros]
     }

     def goLibros(){
     	render view:"libro"
     }

     def guardarReserva() {
        def reserva = new Reservas(estudiante:estudiante.getId(),fecha:params.fecha,libro:params.selectLibros)
        reserva.save(flush:true,failOnError:true)
        redirect view:"index"
     }

     def eliminarReserva() {
        def reserva = Reservas.get(params.id)
        reserva.delete(flush:true,failOnError:true)
        redirect view:"index"
     }
}

Universidad/grails-app/views/libro/agregarLibro.gsp
<!DOCTYPE html>
<html>
<head>
	<title>Agregar Libro</title>
	<asset:stylesheet src="bootstrap.css"/>
	<asset:stylesheet src="materia.css"/>
</head>
<body>
	<g:link action="index" class="btn btn-danger btn-back" controller="libro">
		Regresar
	</g:link>
	<hr>
	<div class="container-fluid">
		<h2>Agregar Libro</h2>
	</div>

	<div class="container-fluid">
		<g:form name="libroForm" class="form" action="guardarLibro">
		<div class="form-group">
			<input type="text" class="form-control" name="nombre" placeholder="Nombre" maxlength="100" required>
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
		</div>
		</g:form>
	</div>
</body>
</html>

Universidad/grails-app/views/libro/editarLibro.gsp
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Materia</title>
    <asset:stylesheet src="bootstrap.css"/>
    <asset:stylesheet src="materia.css"/>
</head>
<body>
<g:link action="index" class="btn btn-danger btn-back" controller="libro">
    Regresar
</g:link>
<hr>
<div class="container-fluid">
    <h2>Editar Libro</h2>
</div>

<div class="container-fluid">
    <g:form name="libroForm" class="form" action="updateLibro">
        <div class="form-group">
            <input type="text" class="form-control" name="id" placeholder="id" maxlength="20" value="${libro.id}" readonly="">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" name="nombre" placeholder="Nombre" maxlength="100" value="${libro.nombre}" required>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" name="submit" value="guardar">
        </div>
    </g:form>
</div>
</body>
</html>

Universidad/grails-app/views/libro/libro.gsp
<!DOCTYPE html>
<html>
<head>
	<title>Libros</title>
	<asset:stylesheet src="bootstrap.css"/>
	<asset:stylesheet src="materia.css"/>
</head>
<body>
	<g:link action="index" class="btn btn-danger btn-back" controller="reservas">
		Regresar
	</g:link>
	<hr>
	<div class="container-fluid">
	<h2>Libros</h2>
	<g:link action="agregarLibro" class="btn btn-primary" controller="libro">
		Agregar Libro
	</g:link>
	</div>
	<div class="container-fluid">
		<div class="row">
			<table class="table table-striped">
				<thead>
					<th>ID</th>
					<th>Libro</th>
				</thead>
				<tbody>
					<g:each in="${lista}" var="libro">
						<tr>
							<td>${libro.id}</td>
							<td>${libro.nombre}</td>
							<td>
								<g:link action="editarLibro" class="btn btn-warning" controller="libro" id="${libro.id}">
									Editar
								</g:link>
								<g:link action="eliminarLibro" class="btn btn-danger" controller="libro" id="${libro.id}">
									Eliminar
								</g:link>
							</td>
						</tr>
					</g:each>
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>